services:
  postgres:
    image: postgres:16
    container_name: postgres-escola
    restart: always
    environment:
      POSTGRES_DB: escola_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - escola-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-escola
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - escola-network

  seq:
    image: datalust/seq:latest
    container_name: seq-escola
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=admin
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin
    ports:
      - "5341:80"
    volumes:
      - seqdata:/data
    networks:
      - escola-network

  professores:
    build:
      context: .
      dockerfile: Professores.API/Dockerfile
    container_name: professores-api
    ports:
      - "5001:80"
    networks:
      - escola-network

  alunos:
    build:
      context: .
      dockerfile: Alunos.API/Dockerfile
    container_name: alunos-api
    ports:
      - "5003:80"
    networks:
      - escola-network

  grade:
    build:
      context: .
      dockerfile: Grade.API/Dockerfile
    container_name: grade-api
    ports:
      - "5005:80"
    networks:
      - escola-network

  turmas:
    build:
      context: .
      dockerfile: Turmas.API/Dockerfile
    container_name: turmas-api
    ports:
      - "5007:80"
    networks:
      - escola-network

  materias:
    build:
      context: .
      dockerfile: Materias.API/Dockerfile
    container_name: materias-api
    ports:
      - "5009:80"
    networks:
      - escola-network

  gateway:
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    container_name: gateway-escola
    ports:
      - "5000:5000"
    depends_on:
      - professores
      - alunos
      - grade
      - turmas
      - materias
    networks:
      - escola-network

volumes:
  pgdata:
  seqdata:

networks:
  escola-network:
    driver: bridge
